# ============================================
# Override service classes
parameters:
  cerad_tourn.officials.export_xls.class: Cerad\Bundle\AppBundle\ServicesAdmin\Persons\PersonsExportXLS
    
  cerad_person.aysov_referee_badge.form_type.class: Cerad\Bundle\AppBundle\FormType\AYSO\RefereeBadgeFormType  
    
  cerad_game__project__results__export_xls__class: 
    Cerad\Bundle\AppBundle\Action\Project\Results\Export\ResultsExportXLS
    
  cerad_game__project__results_poolplay__export_xls__class: 
    Cerad\Bundle\AppBundle\Action\Project\Results\Export\ResultsPoolplayExportXLS
    
  cerad_game__project__results_playoffs__export_xls__class: 
    Cerad\Bundle\AppBundle\Action\Project\Results\Export\ResultsPlayoffsExportXLS
    
  cerad_game__project__results_sportsmanship__export_xls__class: 
    Cerad\Bundle\AppBundle\Action\Project\Results\Export\ResultsSportsmanshipExportXLS
    
services:
    cerad_app.twig_extension:
        class:  Cerad\Bundle\AppBundle\TwigExtension\AppExtension
        arguments:  
            - '%cerad_project_venues%'
            - '@cerad_game__transformer'
        tags:
            - { name: twig.extension }
            
