parameters:

    cerad_project_project_default: AYSONationalGames2014
    
    cerad_project__project_slug_default: natgames
    
    cerad_project_project_files:
        - "%kernel.root_dir%/config/projects/AYSONationalGames2014.yml"

    cerad_project__game_slot_durations:
      VIP: 50
      U10: 50 
      U12: 60 
      U14: 60 
      U16: 70 
      U19: 80

    cerad_project__project_acl:
      
      # Guest - People not logged in
      allowGuestViewLinks:    true  # Menu bar links
      allowGuestViewTeams:    true  # Teams
      allowGuestViewSchedule: false # Schedule
      allowGuestViewResults:  false # Results
      
      # Users - Probably won't need most of these
      allowUsersViewSchedule:     false # 
      allowUsersViewResults:      false # 
      
      # Referees
      allowRefereeSignups:           false # Referees can signup for poolplay
      allowRefereeSignupsMedalRound: false # Allow referees to sign up for any open game
      
      # Staff Access
      allowStaffAssigning: true # Disable all assigning
      allowStaffScoring:   true # Disable all scoring
      
      