# ====================
# 04 Sep 2013
#
# In an effort to document things, all routes are define here, no included files
# In addition, a RoutesTest will detect changes

# ===============================
# Top pages
cerad_tourn_index:
    path: /
    defaults: { _controller: CeradTournBundle:Welcome:index }
    
cerad_tourn_welcome:
    path: /welcome
    defaults: { _controller: CeradTournBundle:Welcome:welcome }
    
cerad_tourn_home:
    path: /home
    defaults: { _controller: CeradTournBundle:Home:home }
    
cerad_tourn_help:
    path: /help
    defaults: { _controller: CeradTournBundle:Help:help }
    
cerad_tourn_contact:
    path: /contact
    defaults: { _controller: CeradTournBundle:Contact:contact }

