cerad_tourn_admin:
    resource: "@CeradTournAdminBundle/Resources/config/routing.yml"
    prefix:   /
    
cerad_app:
    resource: "@CeradAppBundle/Resources/config/routing.yml"
    prefix:   /

cerad_app_admin:
    resource: "@CeradAppBundle/Resources/config/routing_admin.yml"
    prefix:   /
    
cerad_game__routes:
    resource: "@CeradGameBundle/Resources/config/routing.yml"
    prefix:   /
