parameters:
  
  cerad_project_venues:
    'Columbia Park': 
      link: 'http://50.ayso.org/wp-content/uploads/2014/05/maps-columbia.jpg'
    'Field of Dreams': 
      link: 'http://50.ayso.org/wp-content/uploads/2014/05/maps-dreams-300x257.jpg'
    'Ladera Linda': 
      link: 'http://50.ayso.org/wp-content/uploads/2014/05/maps-ladera-linda.jpg'
    'Toyota Sports Complex': 
      link: 'http://50.ayso.org/wp-content/uploads/2014/05/maps-555maple3.jpg'
    'Parras MS': 
      link: 'http://50.ayso.org/wp-content/uploads/2014/05/maps-parrass.jpg'
    'Redondo Union HS': 
      link: 'http://50.ayso.org/wp-content/uploads/2014/05/maps-redondo-union.jpg'
    'West Torrance HS': 
      link: 'http://50.ayso.org/wp-content/uploads/2014/05/maps-westhigh.jpg'
    'Wilson Park'               : 
      link: 'http://50.ayso.org/wp-content/uploads/2014/05/maps-wilson.jpg'
    'WP'               : 
      link: 'http://50.ayso.org/wp-content/uploads/2014/05/maps-wilson.jpg'
    'Ab Brown Sports Complex':
      link: 'http://50.ayso.org/downloads/maps-abbrown.pdf'
    'Reid Park':
      link: 'http://50.ayso.org/downloads/maps-reid.pdf'
    
